spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
      password: ENC(cd+JuGtDgspN8mxaqtxB5zGtmpipizDIG+9nVgBVLa40quv9ue/+VCuG07UkZR7D)
